# cloudbuild will be triggered by push to staging branch
#

steps:
options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
- name: "gce.io/google.com/cloudsdktool/cloud.sdk"
  args: ["echo","Building..."]
