# cloudbuild will be triggered by push to staging branch
#

steps:
options:
  default_logs_bucket_behavior: 0
- name: "gce.io/google.com/cloudsdktool/cloud.sdk"
  args: ["echo","Building..."]
substitutions:
    _FUNCTION_PROJECT: Libra
    _FUNCTION_NAME: my-app-1
    _FUNCTION_REGION: europe-west3
    _FUNCTION_RUNTIME: nodejs20
    _ENTRY_POINT:  helloHttp
